---
title: "Data import"
output: github_document
---

```{r, echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Data Import: CSVs

Let's import data using the 'reader' package

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor :: clean_names(litters_df)
```

Look at the data
```{r}
litters_df
```

head(litters_df)
tail(litters_df)

```{r, eval = FALSE}
view(lutters_df)
```

```{r}
skimr::skim(litters_df)
```

"read_csv" options

```{r}
read.csv("data/FAS_litters.csv", na = c("", "NA"), skip = 2)
```

## Other file formats

We need to read in excel spreadsheet ....

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r,, eval = FALSE}
View(mlb_df)
```

```{r}
lotr_words_df = 
  read_excel(
    "data/mlb11.xlsx", 
    range = "B3:D6"
  )
```

## Still more formats ...
 
 Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

## Data export

```{r}
write_csv(lotr_words_df, file = "data/lotr_words_df.csv")
```

## Why not base r???

```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
```

## .gitignore --> data/lotr_words_df.csv









